apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sample-networkpolicy
  namespace: default
spec:
  podSelector:
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    ports:
  egress:
  - to:
    ports: