apiVersion: v1
kind: Pod
metadata:
    name: sample-projected
spec:
    containers:
    - image: nginx:1.12
      name: nginx-container
      volumeMounts:
      - mountPath: /srv
        name: projected-volume
    volumes:
    - name: projected-volume
      projected:
        sources:
        - secret:
          name: sample-db-auth
          items:
            - key: username
              path: secret/username.txt
          