apiVersion: v1
kind: LimitRange
metadata:
    name: sampple-limitrange-pvc
    namespace: default
spec:
    limits:
    - type: PersistentVolumeClaim
      max:
        storage: 10Gi
      min:
        storage: 3Gi