apiVersion: v1
kind: Pod
metadata:
  name: sample-healthcheck
  labels:
    app: sample-app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.12
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
        scheme: HTTP
      timeoutSecounds: 1
      successThreshold: 1
      failureThreshold: 2
      initialDelaySecounds: 5
      periodSecounds: 3
    readinessProbe:
      exec:
        command: ["ls", "/usr/share/nginx/html/50x.html"]
      timeoutSeconds: 1
      successThreshold: 2
      failureThreshold: 1
      initialDelaySecounds: 5
      periodSecounds: 3