apiVersion: v1
kind: Service
metadata:
    name: sample-externaldip
spec:
    type: ClusterIP
    externalIPs: 
        - 10.240.0.7
        - 10.240.0.8
    ports:
        - name: "http-ports"
          protocol: "TCP"
          port: 8080
          targetPort: 80
    selector:
        app: sample-app
