apiVersion: v1
kind: Pod
metadata:
    name: sample-pod-upper
spec:
    containers:
        - name: nginx-container
          image: nginx:1.13
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 2048Mi
              cpu: 1000m
